import type { MeetingType } from "@/db/schema/meetings";
import {
  churchHasNoPlanter,
  type ChurchLeadershipStatus,
} from "@/lib/onboarding/leadership";

/**
 * The canonical assignee decision for tasks generated by attendance finalization.
 * Finalization itself never depends on this result: a non-vision meeting, an
 * explicit no-planter church, or a church with no Owner still finalizes without
 * generating task rows.
 */
export function meetingFinalizationTaskAssigneeId(input: {
  meetingType: MeetingType;
  leadershipStatus: ChurchLeadershipStatus | null;
  ownerId: string | null;
}): string | null {
  if (
    input.meetingType !== "vision_meeting" ||
    churchHasNoPlanter({ leadershipStatus: input.leadershipStatus })
  ) {
    return null;
  }

  return input.ownerId;
}
