import ExcelJS from "exceljs";
import JSZip from "jszip";
import { XMLParser } from "fast-xml-parser";
import { z } from "zod";
import type { DocumentPreview, WordPreviewBlock } from "./preview-model";

interface WordNode {
  [key: string]: string | WordNode[] | Record<string, string>;
}
const wordNode: z.ZodType<WordNode> = z.lazy(() =>
  z.record(
    z.string(),
    z.union([z.string(), z.array(wordNode), z.record(z.string(), z.string())])
  )
);
const parser = new XMLParser({
  preserveOrder: true,
  ignoreAttributes: false,
  parseTagValue: false,
  parseAttributeValue: false,
});
function children(node: WordNode, key: string): WordNode[] {
  const value = node[key];
  return Array.isArray(value) ? value : [];
}
function text(nodes: WordNode[]): string {
  return nodes
    .map((node) =>
      Object.entries(node)
        .map(([key, value]) => {
          if (key === "#text") return typeof value === "string" ? value : "";
          if (key === "w:tab") return "\t";
          if (key === "w:br") return "\n";
          return Array.isArray(value) ? text(value) : "";
        })
        .join("")
    )
    .join("");
}
function wordBlocks(nodes: WordNode[]): WordPreviewBlock[] {
  const result: WordPreviewBlock[] = [];
  for (const node of nodes) {
    if (node["w:p"]) {
      const paragraph = children(node, "w:p");
      const properties = paragraph.flatMap((item) => children(item, "w:pPr"));
      const style = properties.find((item) => item["w:pStyle"])?.[":@"];
      const heading =
        !!style &&
        !Array.isArray(style) &&
        typeof style === "object" &&
        /^(Title|Heading)/.test(style["@_w:val"] ?? "");
      result.push({ kind: "paragraph", text: text(paragraph), heading });
    } else if (node["w:tbl"]) {
      const rows = children(node, "w:tbl")
        .filter((row) => row["w:tr"])
        .map((row) =>
          children(row, "w:tr")
            .filter((cell) => cell["w:tc"])
            .map((cell) =>
              wordBlocks(children(cell, "w:tc"))
                .map((block) =>
                  block.kind === "paragraph"
                    ? block.text
                    : block.rows.map((row) => row.join("\t")).join("\n")
                )
                .join("\n")
            )
        );
      result.push({ kind: "table", rows });
    } else {
      for (const [key, value] of Object.entries(node))
        if (key !== ":@" && Array.isArray(value))
          result.push(...wordBlocks(value));
    }
  }
  return result;
}

/** Read the actual generated bytes, so preview never carries a second copy of template content. */
export async function previewDocumentBytes(
  format: "docx" | "xlsx",
  bytes: Buffer
): Promise<DocumentPreview> {
  if (bytes.length > 8 * 1024 * 1024)
    throw new Error("Document exceeds preview size limit");
  if (format === "docx") {
    const zip = await JSZip.loadAsync(bytes);
    const parts = [
      "word/document.xml",
      ...Object.keys(zip.files)
        .filter((name) => /^word\/footer\d+\.xml$/.test(name))
        .sort(),
    ];
    const blocks: WordPreviewBlock[] = [];
    for (const name of parts) {
      const file = zip.file(name);
      if (!file) throw new Error("Document preview part missing");
      const xml = await file.async("string");
      if (xml.length > 2_000_000)
        throw new Error("Document exceeds preview size limit");
      blocks.push(...wordBlocks(z.array(wordNode).parse(parser.parse(xml))));
    }
    if (blocks.length > 1000)
      throw new Error("Document exceeds preview block limit");
    return { format, blocks };
  }
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(new Uint8Array(bytes).buffer);
  if (workbook.worksheets.length > 20)
    throw new Error("Workbook exceeds preview sheet limit");
  return {
    format,
    sheets: workbook.worksheets.map((sheet) => {
      if (sheet.rowCount > 500 || sheet.columnCount > 50)
        throw new Error("Worksheet exceeds preview dimensions");
      return {
        name: sheet.name,
        rows: Array.from({ length: sheet.rowCount }, (_, row) =>
          Array.from({ length: sheet.columnCount }, (_, column) => {
            const cell = sheet.getCell(row + 1, column + 1);
            return {
              text:
                cell.isMerged && cell.master.address !== cell.address
                  ? ""
                  : cell.text,
              bold: cell.font?.bold ?? false,
              formula: cell.formula ?? null,
            };
          })
        ),
      };
    }),
  };
}
