/**
 * F12 / OB-001 + OB-009 — the flow's completion UPDATE.
 *
 * WHY THIS IS NOT IN THE ACTION. `"use server"` modules are an auth surface —
 * every export is a POSTable endpoint (`memory/invariants.md` →
 * Authentication) — so `dashboard/actions.ts` keeps one job, minting the actor
 * from `verifySession()`, and the statement lives here where the tests can
 * read its SQL. Same shape as `./create-church` (#198) and
 * `./declare-journey`.
 */

import { db } from "@/db";
import { churches } from "@/db/schema";
import { plantDirtyColumns } from "@/lib/phase-engine/dirty-handler";
import { and, eq, isNull } from "drizzle-orm";

/**
 * F12 / OB-001 — the UPDATE that leaves the onboarding flow and hands the
 * dashboard back.
 *
 * Stamping `onboarding_completed_at` is what stops the flow owning
 * `/dashboard`. It records "the planter is done answering", not "every step
 * was answered": skipping straight through from step 1 is a legitimate way to
 * get here (AC 4) and leaves exactly today's outcome — a named church at phase
 * 0 with no launch date. Which facts are still missing stays derivable from the
 * columns themselves, which is what the incomplete-onboarding nudge (OB-011)
 * reads.
 *
 * The `IS NULL` guard makes this idempotent: a double submit, or a second tab,
 * cannot move a completion timestamp that is already set.
 *
 * OB-009 — FINISHING MARKS THE PLANT DIRTY. `last_material_event_at` is stamped
 * in the SAME statement as the completion, because finishing setup IS the
 * material event: a plant that just declared its stage, its launch date and its
 * people has changed enough to be worth assessing, and without the stamp a brand
 * new plant with no other activity would sit cold behind the 7-day staleness
 * window (`src/lib/phase-engine/assessment/dirty.ts`). One statement rather than
 * a follow-up `markPlantDirty()` call so the two facts cannot disagree, and
 * behind the same `IS NULL` guard so a second submit cannot re-dirty a plant
 * that finished days ago. Marking dirty is all this does — assessments are
 * generated by the daily run, never synchronously from a planter's click.
 */
export function completeOnboardingStatement(
  churchId: string,
  finishedAt: Date
) {
  return db
    .update(churches)
    .set({
      onboardingCompletedAt: finishedAt,
      ...plantDirtyColumns(finishedAt),
    })
    .where(
      and(eq(churches.id, churchId), isNull(churches.onboardingCompletedAt))
    );
}
