-- P-0xx — `persons.background_check_status`: where a volunteer stands in the
-- church's OWN background-check process, recorded by hand.
--
-- WHY A COLUMN ON `persons` AND NOT A TABLE. There is one answer per person at
-- a time and no provider to reconcile with: nothing in this repo talks to a
-- screening service, and the requirement this serves — the Children's Ministry
-- roster showing whether the person in a seat is cleared — reads exactly one
-- current value. A `background_checks` table would buy a history nobody writes
-- and a "which row is current" question every reader would have to answer.
-- When a provider integration lands it will own its own rows and this column
-- becomes the projection they update.
--
-- THE DEFAULT IS `not_started`, AND THAT IS THE BACKFILL. The column is NOT
-- NULL with a default, so Postgres fills EVERY EXISTING ROW with 'not_started'
-- in this statement; there is no separate UPDATE and no window in which a
-- person has no value. Two spellings of "nobody has said" (NULL and
-- 'not_started') would make every reader coalesce them, and a roster is the
-- wrong place to learn the difference between an unanswered question and an
-- unstarted one. Since PostgreSQL 11 a defaulted NOT NULL column is added
-- without rewriting the heap, so this is a catalogue change on a table of any
-- size.
--
-- THE CHECK IS THE VOCABULARY. `.$type<BackgroundCheckStatus>()` on a varchar
-- is a compile-time brand and nothing more — the same reasoning as 0024, 0031,
-- 0032, 0033 and 0040 — so the four legal values are closed in the database
-- too. This column decides whether a roster claims somebody is cleared to work
-- with children, which makes "whatever the last writer happened to spell" a
-- worse answer here than anywhere else it has been refused.
--
-- ADDITIVE, AND EITHER DEPLOY ORDER IS SAFE. One column and one CHECK; nothing
-- is dropped, renamed or rewritten, and no other table is read or written.
-- Code-first is survivable in both directions: the old code never names the
-- column, and the new code reading a database without it fails loudly on
-- `column persons.background_check_status does not exist` rather than
-- half-working. Nothing in this repo applies migrations on deploy
-- (`package.json` has only `"build": "next build"`), so an operator runs
-- `pnpm db:migrate`.
--
-- SIBLING RECONCILE. This migration's `when` is 1786858232298, above 0042's
-- 1786769854360, so a `db:migrate` run reaches it. A migration from another
-- branch merging with a `when` BELOW that is SILENTLY SKIPPED and owes this one
-- a forward reconcile in its own header (memory/invariants.md → Migrations).
--
-- ROLLBACK (HR2). Two statements, in ONE psql session:
--
--   ALTER TABLE "persons" DROP COLUMN IF EXISTS "background_check_status";
--   DELETE FROM drizzle.__drizzle_migrations WHERE created_at = 1786858232298;
--
--   *** DO NOT EDIT src/db/migrations/meta/_journal.json. ***
--
-- Same reasoning as 0023/0024/0031/0032/0033/0040/0042: the journal is the
-- repository's list of migrations, `drizzle.__drizzle_migrations` is the
-- database's record of what ran, and only the ledger row is deleted. Dropping
-- the column also drops the CHECK with it, and FORGETS every recorded status —
-- there is no other copy of it — so revert the application half first and read
-- the non-default rows before running it:
--
--   SELECT background_check_status, count(*) FROM persons
--    WHERE background_check_status <> 'not_started' GROUP BY 1;
--
-- The ledger row can also be identified by the sha256 of THIS FILE, byte for
-- byte, from the deployed commit:
--
--   shasum -a 256 src/db/migrations/0043_person_background_check_status.sql
ALTER TABLE "persons" ADD COLUMN "background_check_status" varchar(20) DEFAULT 'not_started' NOT NULL;--> statement-breakpoint
ALTER TABLE "persons" ADD CONSTRAINT "persons_background_check_status_check" CHECK ("persons"."background_check_status" in ('not_started', 'in_progress', 'cleared', 'flagged'));
