#!/usr/bin/env bash
set -euo pipefail

LANGFUSE_OPS_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
LANGFUSE_ENV_FILE="$LANGFUSE_OPS_DIR/.env"
LANGFUSE_COMPOSE_FILE="$LANGFUSE_OPS_DIR/compose.yaml"
LANGFUSE_PROJECT_NAME=everyfield-langfuse

langfuse_die() {
  printf 'langfuse: %s\n' "$*" >&2
  exit 1
}

langfuse_require_command() {
  command -v "$1" >/dev/null 2>&1 || langfuse_die "required command not found: $1"
}

langfuse_random_hex() {
  openssl rand -hex "$1"
}

langfuse_read_env() {
  local langfuse_key=$1
  awk -F= -v key="$langfuse_key" '$1 == key { print substr($0, index($0, "=") + 1) }' "$LANGFUSE_ENV_FILE"
}

langfuse_compose() {
  docker compose \
    --project-name "$LANGFUSE_PROJECT_NAME" \
    --env-file "$LANGFUSE_ENV_FILE" \
    --file "$LANGFUSE_COMPOSE_FILE" \
    "$@"
}

langfuse_init() {
  langfuse_require_command openssl

  if [[ -e "$LANGFUSE_ENV_FILE" ]]; then
    langfuse_validate_env
    printf 'Langfuse local credentials already exist at %s\n' "$LANGFUSE_ENV_FILE"
    return
  fi

  local langfuse_temp_dir
  local langfuse_temp_env
  langfuse_temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/everyfield-langfuse-init.XXXXXX")
  langfuse_temp_env="$langfuse_temp_dir/.env"
  trap 'rm -rf "$langfuse_temp_dir"' RETURN
  umask 077

  {
    printf '%s\n' '# Generated by ops/langfuse/manage.sh init. Local-only; do not commit.'
    printf '%s\n' 'LANGFUSE_WEB_HOST_PORT=3210'
    printf '%s\n' 'LANGFUSE_WORKER_HOST_PORT=3230'
    printf '%s\n' 'LANGFUSE_CLICKHOUSE_HTTP_HOST_PORT=3213'
    printf '%s\n' 'LANGFUSE_CLICKHOUSE_NATIVE_HOST_PORT=3300'
    printf '%s\n' 'LANGFUSE_MINIO_API_HOST_PORT=3290'
    printf '%s\n' 'LANGFUSE_MINIO_CONSOLE_HOST_PORT=3291'
    printf '%s\n' 'LANGFUSE_REDIS_HOST_PORT=3279'
    printf '%s\n' 'LANGFUSE_POSTGRES_HOST_PORT=3243'
    printf 'POSTGRES_PASSWORD=%s\n' "$(langfuse_random_hex 24)"
    printf 'CLICKHOUSE_PASSWORD=%s\n' "$(langfuse_random_hex 24)"
    printf 'MINIO_ROOT_PASSWORD=%s\n' "$(langfuse_random_hex 24)"
    printf 'REDIS_AUTH=%s\n' "$(langfuse_random_hex 24)"
    printf 'LANGFUSE_SALT=%s\n' "$(langfuse_random_hex 24)"
    printf 'LANGFUSE_ENCRYPTION_KEY=%s\n' "$(langfuse_random_hex 32)"
    printf 'LANGFUSE_NEXTAUTH_SECRET=%s\n' "$(langfuse_random_hex 32)"
    printf '%s\n' 'LANGFUSE_INIT_ORG_ID=everyfield-local'
    printf '%s\n' 'LANGFUSE_INIT_ORG_NAME=EveryField-local'
    printf '%s\n' 'LANGFUSE_INIT_PROJECT_ID=everyfield-local'
    printf '%s\n' 'LANGFUSE_INIT_PROJECT_NAME=EveryField-local'
    printf 'LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-%s\n' "$(langfuse_random_hex 24)"
    printf 'LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-%s\n' "$(langfuse_random_hex 24)"
    printf '%s\n' 'LANGFUSE_INIT_USER_EMAIL=langfuse-admin@everyfield.local'
    printf '%s\n' 'LANGFUSE_INIT_USER_NAME=EveryField-local-admin'
    printf 'LANGFUSE_INIT_USER_PASSWORD=%s\n' "$(langfuse_random_hex 24)"
  } >"$langfuse_temp_env"

  chmod 600 "$langfuse_temp_env"
  mv "$langfuse_temp_env" "$LANGFUSE_ENV_FILE"
  trap - RETURN
  rm -rf "$langfuse_temp_dir"
  langfuse_validate_env
  printf 'Created local-only Langfuse credentials at %s\n' "$LANGFUSE_ENV_FILE"
}

langfuse_validate_env() {
  [[ -f "$LANGFUSE_ENV_FILE" ]] || langfuse_die "missing $LANGFUSE_ENV_FILE; run ./ops/langfuse/manage.sh init"

  local langfuse_env_mode
  if langfuse_env_mode=$(stat -f '%Lp' "$LANGFUSE_ENV_FILE" 2>/dev/null); then
    :
  else
    langfuse_env_mode=$(stat -c '%a' "$LANGFUSE_ENV_FILE")
  fi
  [[ "$langfuse_env_mode" == 600 ]] || langfuse_die "$LANGFUSE_ENV_FILE must have mode 600"

  local -a langfuse_required_keys=(
    LANGFUSE_WEB_HOST_PORT LANGFUSE_WORKER_HOST_PORT
    LANGFUSE_CLICKHOUSE_HTTP_HOST_PORT LANGFUSE_CLICKHOUSE_NATIVE_HOST_PORT
    LANGFUSE_MINIO_API_HOST_PORT LANGFUSE_MINIO_CONSOLE_HOST_PORT
    LANGFUSE_REDIS_HOST_PORT LANGFUSE_POSTGRES_HOST_PORT
    POSTGRES_PASSWORD CLICKHOUSE_PASSWORD MINIO_ROOT_PASSWORD REDIS_AUTH
    LANGFUSE_SALT LANGFUSE_ENCRYPTION_KEY LANGFUSE_NEXTAUTH_SECRET
    LANGFUSE_INIT_ORG_ID LANGFUSE_INIT_ORG_NAME
    LANGFUSE_INIT_PROJECT_ID LANGFUSE_INIT_PROJECT_NAME
    LANGFUSE_INIT_PROJECT_PUBLIC_KEY LANGFUSE_INIT_PROJECT_SECRET_KEY
    LANGFUSE_INIT_USER_EMAIL LANGFUSE_INIT_USER_NAME LANGFUSE_INIT_USER_PASSWORD
  )
  local langfuse_key
  local langfuse_value
  for langfuse_key in "${langfuse_required_keys[@]}"; do
    [[ $(grep -Ec "^${langfuse_key}=" "$LANGFUSE_ENV_FILE") -eq 1 ]] || langfuse_die "$langfuse_key must occur exactly once in $LANGFUSE_ENV_FILE"
    langfuse_value=$(langfuse_read_env "$langfuse_key")
    [[ -n "$langfuse_value" ]] || langfuse_die "$langfuse_key must not be empty"
    [[ "$langfuse_value" =~ ^[A-Za-z0-9@._:/=-]+$ ]] || langfuse_die "$langfuse_key contains unsupported characters"
  done

  local -a langfuse_ports=()
  for langfuse_key in "${langfuse_required_keys[@]:0:8}"; do
    langfuse_value=$(langfuse_read_env "$langfuse_key")
    [[ "$langfuse_value" =~ ^[0-9]+$ ]] || langfuse_die "$langfuse_key must be a numeric port"
    ((langfuse_value >= 1024 && langfuse_value <= 65535)) || langfuse_die "$langfuse_key must be between 1024 and 65535"
    [[ ! " ${langfuse_ports[*]-} " =~ " ${langfuse_value} " ]] || langfuse_die "host port $langfuse_value is assigned more than once"
    langfuse_ports+=("$langfuse_value")
  done

  [[ $(langfuse_read_env LANGFUSE_ENCRYPTION_KEY) =~ ^[0-9a-f]{64}$ ]] || langfuse_die 'LANGFUSE_ENCRYPTION_KEY must be 64 lowercase hex characters'
  [[ $(langfuse_read_env LANGFUSE_INIT_PROJECT_PUBLIC_KEY) =~ ^pk-lf-[0-9a-f]{48}$ ]] || langfuse_die 'invalid LANGFUSE_INIT_PROJECT_PUBLIC_KEY'
  [[ $(langfuse_read_env LANGFUSE_INIT_PROJECT_SECRET_KEY) =~ ^sk-lf-[0-9a-f]{48}$ ]] || langfuse_die 'invalid LANGFUSE_INIT_PROJECT_SECRET_KEY'

  if grep -Eq '^(OPENAI_API_KEY|ANTHROPIC_API_KEY|GOOGLE_GENERATIVE_AI_API_KEY|GOOGLE_API_KEY|AZURE_OPENAI_API_KEY|MISTRAL_API_KEY|GROQ_API_KEY|COHERE_API_KEY|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|LANGFUSE_AI_API_KEY)=' "$LANGFUSE_ENV_FILE"; then
    langfuse_die 'model-provider credentials are forbidden in the local Langfuse environment'
  fi
}

langfuse_check_config() {
  langfuse_require_command docker
  langfuse_require_command jq
  langfuse_validate_env

  [[ $(grep -Ec '^[[:space:]]*<level>information</level>[[:space:]]*$' "$LANGFUSE_OPS_DIR/clickhouse-logger.xml") == 1 ]] ||
    langfuse_die 'ClickHouse logger level must remain information'
  [[ $(grep -Ec '^[[:space:]]*<size>50M</size>[[:space:]]*$' "$LANGFUSE_OPS_DIR/clickhouse-logger.xml") == 1 ]] ||
    langfuse_die 'ClickHouse logger rotation size must remain 50M'
  [[ $(grep -Ec '^[[:space:]]*<count>3</count>[[:space:]]*$' "$LANGFUSE_OPS_DIR/clickhouse-logger.xml") == 1 ]] ||
    langfuse_die 'ClickHouse logger archive count must remain 3'

  local langfuse_temp_dir
  local langfuse_config_json
  langfuse_temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/everyfield-langfuse-config.XXXXXX")
  langfuse_config_json="$langfuse_temp_dir/compose.json"
  trap 'rm -rf "$langfuse_temp_dir"' RETURN
  umask 077
  langfuse_compose config --format json >"$langfuse_config_json"

  jq -e '
    .services["langfuse-web"].image == "docker.langfuse.com/langfuse/langfuse:4.22.0" and
    .services["langfuse-worker"].image == "docker.langfuse.com/langfuse/langfuse-worker:4.22.0" and
    .services.clickhouse.image == "docker.io/clickhouse/clickhouse-server:25.12" and
    .services.minio.image == "cgr.dev/chainguard/minio:latest" and
    .services.redis.image == "docker.io/redis:7" and
    .services.postgres.image == "docker.io/postgres:17"
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'rendered compose images do not match the v4.22.0 topology'

  jq -e '
    [.services.clickhouse.volumes[] |
      select(
        .type == "bind" and
        .target == "/etc/clickhouse-server/config.d/everyfield-logger.xml" and
        .read_only == true
      )
    ] | length == 1
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'ClickHouse log retention configuration must remain mounted read-only'

  jq -e '
    ([.services[] | .ports[]? | select(.published != null)] | length) > 0 and
    ([.services[] | .ports[]? | select(.published != null) | .host_ip] | all(. == "127.0.0.1")) and
    ([.services[] | .ports[]? | select(.published != null) | .published] | unique | length) ==
      ([.services[] | .ports[]? | select(.published != null) | .published] | length) and
    ([.services[] | .ports[]? | select(.published != null and ((.published | tonumber) == .target))] | length) == 0
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'every published port must be unique, loopback-only, and remapped from its service default'

  jq -e '
    [.services["langfuse-web"], .services["langfuse-worker"]] |
    all(
      .environment.TELEMETRY_ENABLED == "false" and
      .environment.LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES == "false" and
      .environment.LANGFUSE_IN_APP_AGENT_ENABLED == "false"
    )
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'telemetry, experimental features, and the in-app agent must remain disabled'

  jq -e '
    [.services[]] |
    all(
      .logging.driver == "local" and
      .logging.options["max-size"] == "10m" and
      .logging.options["max-file"] == "3"
    )
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'every service must use bounded local Docker logs'

  jq -e '
    [.services[] | (.environment // {}) | keys[] |
      select(test("^(OPENAI_API_KEY|ANTHROPIC_API_KEY|GOOGLE_GENERATIVE_AI_API_KEY|GOOGLE_API_KEY|AZURE_OPENAI_API_KEY|MISTRAL_API_KEY|GROQ_API_KEY|COHERE_API_KEY|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|LANGFUSE_AI_API_KEY)$"))
    ] | length == 0
  ' "$langfuse_config_json" >/dev/null || langfuse_die 'rendered compose config contains a forbidden model-provider credential slot'

  trap - RETURN
  rm -rf "$langfuse_temp_dir"
  printf '%s\n' 'Langfuse compose configuration is valid and provider-key-free.'
}

langfuse_pull_missing_images() {
  local -a langfuse_public_images=(
    docker.langfuse.com/langfuse/langfuse:4.22.0
    docker.langfuse.com/langfuse/langfuse-worker:4.22.0
    docker.io/clickhouse/clickhouse-server:25.12
    cgr.dev/chainguard/minio:latest
    docker.io/redis:7
    docker.io/postgres:17
  )
  local langfuse_docker_config_dir
  local langfuse_image
  langfuse_docker_config_dir=$(mktemp -d "${TMPDIR:-/tmp}/everyfield-langfuse-docker-config.XXXXXX")
  trap 'rm -rf "$langfuse_docker_config_dir"' RETURN
  chmod 700 "$langfuse_docker_config_dir"

  for langfuse_image in "${langfuse_public_images[@]}"; do
    if ! docker image inspect "$langfuse_image" >/dev/null 2>&1; then
      docker --config "$langfuse_docker_config_dir" pull "$langfuse_image"
    fi
  done

  trap - RETURN
  rm -rf "$langfuse_docker_config_dir"
}

langfuse_wait_for_url() {
  local langfuse_url=$1
  local langfuse_attempt
  for langfuse_attempt in $(seq 1 90); do
    if curl --fail --silent --show-error --max-time 5 "$langfuse_url" >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done
  langfuse_die "timed out waiting for $langfuse_url"
}

langfuse_write_netrc() {
  local langfuse_target=$1
  umask 077
  {
    printf '%s\n' 'machine 127.0.0.1'
    printf 'login %s\n' "$(langfuse_read_env LANGFUSE_INIT_PROJECT_PUBLIC_KEY)"
    printf 'password %s\n' "$(langfuse_read_env LANGFUSE_INIT_PROJECT_SECRET_KEY)"
  } >"$langfuse_target"
  chmod 600 "$langfuse_target"
}

langfuse_health() {
  langfuse_require_command curl
  langfuse_require_command jq
  langfuse_validate_env

  local langfuse_web_port
  local langfuse_worker_port
  local langfuse_base_url
  local langfuse_temp_dir
  local langfuse_netrc
  local langfuse_status
  langfuse_web_port=$(langfuse_read_env LANGFUSE_WEB_HOST_PORT)
  langfuse_worker_port=$(langfuse_read_env LANGFUSE_WORKER_HOST_PORT)
  langfuse_base_url="http://127.0.0.1:$langfuse_web_port"

  langfuse_wait_for_url "$langfuse_base_url/api/public/health?failIfDatabaseUnavailable=true"
  langfuse_wait_for_url "$langfuse_base_url/api/public/ready"
  langfuse_wait_for_url "http://127.0.0.1:$langfuse_worker_port/api/health"
  langfuse_wait_for_url "http://127.0.0.1:$langfuse_worker_port/api/ready"

  curl --fail --silent --show-error --max-time 10 \
    "$langfuse_base_url/api/public/health?failIfDatabaseUnavailable=true" |
    jq -e '.status == "OK" and .version == "4.22.0"' >/dev/null || langfuse_die 'web health response is not Langfuse 4.22.0 OK'

  langfuse_temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/everyfield-langfuse-health.XXXXXX")
  langfuse_netrc="$langfuse_temp_dir/netrc"
  trap 'rm -rf "$langfuse_temp_dir"' RETURN
  langfuse_write_netrc "$langfuse_netrc"

  langfuse_status=$(curl --silent --output /dev/null --write-out '%{http_code}' --max-time 10 "$langfuse_base_url/api/public/projects")
  [[ "$langfuse_status" == 401 ]] || langfuse_die "public API without credentials returned $langfuse_status instead of 401"
  langfuse_status=$(curl --silent --output /dev/null --write-out '%{http_code}' --max-time 10 --user invalid:invalid "$langfuse_base_url/api/public/projects")
  [[ "$langfuse_status" == 401 ]] || langfuse_die "public API with invalid credentials returned $langfuse_status instead of 401"
  curl --fail --silent --show-error --max-time 10 --netrc-file "$langfuse_netrc" "$langfuse_base_url/api/public/projects" |
    jq -e --arg project_id "$(langfuse_read_env LANGFUSE_INIT_PROJECT_ID)" '.data | any(.id == $project_id)' >/dev/null ||
    langfuse_die 'headless project credentials were not authenticated'

  trap - RETURN
  rm -rf "$langfuse_temp_dir"
  printf 'Langfuse 4.22.0 is healthy, ready, and authenticated at %s\n' "$langfuse_base_url"
}

langfuse_up() {
  langfuse_init
  langfuse_check_config
  langfuse_pull_missing_images
  langfuse_compose up --detach --wait --wait-timeout 300
  langfuse_health
}

langfuse_smoke() {
  langfuse_require_command curl
  langfuse_require_command jq
  langfuse_require_command openssl
  langfuse_health

  local langfuse_web_port langfuse_base_url langfuse_trace_id langfuse_span_id
  local langfuse_correlation_id langfuse_now_seconds langfuse_start_nanos langfuse_end_nanos
  local langfuse_temp_dir langfuse_netrc langfuse_payload langfuse_response
  local langfuse_status langfuse_attempt
  langfuse_web_port=$(langfuse_read_env LANGFUSE_WEB_HOST_PORT)
  langfuse_base_url="http://127.0.0.1:$langfuse_web_port"
  langfuse_trace_id=$(langfuse_random_hex 16)
  langfuse_span_id=$(langfuse_random_hex 8)
  langfuse_correlation_id="local-smoke-$langfuse_trace_id"
  langfuse_now_seconds=$(date +%s)
  langfuse_start_nanos=$((langfuse_now_seconds * 1000000000))
  langfuse_end_nanos=$((langfuse_start_nanos + 1000000))

  langfuse_temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/everyfield-langfuse-smoke.XXXXXX")
  langfuse_netrc="$langfuse_temp_dir/netrc"
  langfuse_payload="$langfuse_temp_dir/trace.json"
  langfuse_response="$langfuse_temp_dir/response.json"
  trap 'rm -rf "$langfuse_temp_dir"' RETURN
  langfuse_write_netrc "$langfuse_netrc"

  jq -n --arg trace_id "$langfuse_trace_id" --arg span_id "$langfuse_span_id" \
    --arg correlation_id "$langfuse_correlation_id" --arg start_nanos "$langfuse_start_nanos" --arg end_nanos "$langfuse_end_nanos" \
    '{resourceSpans: [{resource: {attributes: [
      {key: "service.name", value: {stringValue: "everyfield-langfuse-smoke"}},
      {key: "deployment.environment.name", value: {stringValue: "local-smoke"}}
    ]}, scopeSpans: [{scope: {name: "everyfield.ops.langfuse", version: "1"}, spans: [{
      traceId: $trace_id, spanId: $span_id, name: "everyfield-zero-provider-smoke", kind: 1,
      startTimeUnixNano: $start_nanos, endTimeUnixNano: $end_nanos,
      attributes: [
        {key: "langfuse.internal.is_app_root", value: {boolValue: true}},
        {key: "langfuse.trace.name", value: {stringValue: "everyfield-zero-provider-smoke"}},
        {key: "everyfield.correlation_id", value: {stringValue: $correlation_id}},
        {key: "everyfield.provider_calls", value: {intValue: "0"}}
      ], status: {code: 1}
    }]}]}]}' >"$langfuse_payload"

  langfuse_status=$(curl --silent --show-error --output "$langfuse_response" --write-out '%{http_code}' --max-time 30 \
    --netrc-file "$langfuse_netrc" --header 'Content-Type: application/json' --header 'x-langfuse-ingestion-version: 4' \
    --data-binary "@$langfuse_payload" "$langfuse_base_url/api/public/otel/v1/traces")
  [[ "$langfuse_status" == 200 ]] || langfuse_die "OTLP smoke ingestion returned HTTP $langfuse_status"

  for langfuse_attempt in $(seq 1 60); do
    langfuse_status=$(curl --silent --show-error --output "$langfuse_response" --write-out '%{http_code}' --max-time 15 \
      --netrc-file "$langfuse_netrc" --get --data-urlencode 'fields=core,basic,metadata' \
      --data-urlencode "traceId=$langfuse_trace_id" "$langfuse_base_url/api/public/v2/observations")
    if [[ "$langfuse_status" == 200 ]] && jq -e --arg trace_id "$langfuse_trace_id" '.data | any(.traceId == $trace_id)' "$langfuse_response" >/dev/null; then
      trap - RETURN
      rm -rf "$langfuse_temp_dir"
      printf 'Provider-free OTLP smoke passed (trace_id=%s correlation_id=%s provider_calls=0).\n' "$langfuse_trace_id" "$langfuse_correlation_id"
      return
    fi
    sleep 2
  done
  langfuse_die "smoke trace $langfuse_trace_id was accepted but not readable within 120 seconds"
}

langfuse_down() {
  if [[ ! -f "$LANGFUSE_ENV_FILE" ]]; then
    printf '%s\n' 'Langfuse is already down (no local environment file).'
    return
  fi
  langfuse_validate_env
  langfuse_compose down --volumes --remove-orphans --timeout 30
  printf '%s\n' 'Langfuse containers, network, and named data volumes are down.'
}

langfuse_usage() {
  cat <<'EOF'
Usage: ./ops/langfuse/manage.sh <command>

Commands:
  init    Create a gitignored, mode-600 local credential file if absent.
  check   Validate rendered compose topology, ports, opt-outs, and key absence.
  up      Idempotently initialize, validate, start, and health-check the stack.
  health  Check web/worker health and readiness plus public API auth boundaries.
  smoke   Ingest and read back one metadata-only OTLP span; calls no model provider.
  down    Idempotently stop the stack and delete its local data volumes.
EOF
}

case "${1:-}" in
  init) langfuse_init ;;
  check) langfuse_check_config ;;
  up) langfuse_up ;;
  health) langfuse_health ;;
  smoke) langfuse_smoke ;;
  down) langfuse_down ;;
  *) langfuse_usage; [[ $# -eq 0 ]] || exit 1 ;;
esac
